# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAuthsuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginadminerror(self):
    self.driver.get("http://127.0.0.1:5000/admin/login")
    self.driver.set_window_size(1055, 600)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("admin@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("WrongPassword")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").send_keys(Keys.ENTER)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".fw-light")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".fw-light").text == "Login"
  
  def test_logout(self):
    self.driver.get("http://127.0.0.1:5000/admin/login")
    self.driver.set_window_size(1055, 600)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("admin@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Admin$00")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").send_keys(Keys.ENTER)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".navbar-brand")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand").text == "NBA Project Nicolà Bertolazzi"
    self.driver.find_element(By.XPATH, "//a[@id=\'navbarDropdownUserImage\']/img").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".fw-light").text == "Login"
  
  def test_loginadminvalid(self):
    self.driver.get("http://127.0.0.1:5000/admin/login")
    self.driver.set_window_size(1055, 600)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("admin@gmail.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("Admin$00")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").send_keys(Keys.ENTER)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".navbar-brand")))
    assert self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand").text == "NBA Project Nicolà Bertolazzi"
  
